name: CI
on: 
  push:
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: miRoox/wolfram-action@master
      with:
        file: Build.wls
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
    - name: Run Tests
      uses: miRoox/wolfram-action@master
      with:
        file: RunTests.wls
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
